apiVersion: v1
kind: Service
metadata:
  name: portfolio-service
  namespace: front-end-app
spec:
  selector:
    app: portfolio
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 80
  type: NodePort